
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore NuGet Packages
      run: nuget restore LrcHelper.sln

    - name: Build 
      run: msbuild LrcHelper.sln /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 163lrc_auto_build
        path: D:\a\LrcHelper\LrcHelper\LrcHelper\bin\Release\163lrc.exe
